### ISSUE TITLE
need update of env for JVM? like JVM_HEAP_XMX

### ISSUE THREAD

**Issue by TiloGit** [aws-quickstart/quickstart-ibm-filenet-content-manager#20]
does FN container still support env

```yaml
          - name: JVM_HEAP_XMS
            value: "512m"
          - name: JVM_HEAP_XMX
            value: "2048m"
```

Or do they now require

- JVM_INITIAL_HEAP_PERCENTAGE
- JVM_MAX_HEAP_PERCENTAGE

my pod log
```log
No JVM_INITIAL_HEAP_PERCENTAGE, using default initail heap percentage 18
No JVM_MAX_HEAP_PERCENTAGE, using default max heap percentage 33
No JVM_CUSTOMIZE_OPTIONS provided by the users.
```
